//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public long Id { get; set; }
        public string CustomerName { get; set; }
        public string OppurtunityName { get; set; }
        public string OppurtunityDescription { get; set; }
        public Nullable<long> CiarraID { get; set; }
        public Nullable<long> DealOpportunityStatusId { get; set; }
        public Nullable<long> DealOpportunityTypeId { get; set; }
        public Nullable<long> DealVerticalId { get; set; }
        public Nullable<long> DealRegionId { get; set; }
        public Nullable<long> PractiseId { get; set; }
        public Nullable<long> EstAdditionalTCV { get; set; }
        public Nullable<long> Duration { get; set; }
        public string DealExpClosureQtr { get; set; }
        public Nullable<System.DateTime> DealEngStartDate { get; set; }
        public Nullable<long> DealCurrentStatusId { get; set; }
        public Nullable<long> SubAdditionalTCV { get; set; }
        public Nullable<long> FY16Revenue { get; set; }
        public Nullable<long> Q1Revenue { get; set; }
        public Nullable<long> Q2Revenue { get; set; }
        public Nullable<long> Q3Revenue { get; set; }
        public Nullable<long> Q4Revenue { get; set; }
        public string Competition { get; set; }
        public string CurrSupportReq { get; set; }
        public string WklyRunningUpdates { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> DealFarmingLead { get; set; }
        public Nullable<long> DealVLDNLead { get; set; }
        public Nullable<long> DeliveryLeadId { get; set; }
        public Nullable<long> FarmingAnchorId { get; set; }
        public Nullable<long> VLDNAnchorId { get; set; }
        public Nullable<long> DeliveryAnchorId { get; set; }
        public Nullable<System.DateTime> ContractSignDate { get; set; }
        public string PractiseSME { get; set; }
        public string ItemType { get; set; }
        public string Path { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
